### ISSUE TITLE
not found

### ISSUE THREAD

**Issue by vqoley** [shin202/movevee-api#9]
when i try to access and get any movie or tv streaming link i always got this code:

{
    "status": "error",
    "msg": "Something went wrong. Please try again later!"
}

example my query:
localhost:3000/api/streaming?mediaId=tv/watch-karate-sheep-93742&episodeId=9406897

it is wrong on my side or this code have bug?

**Comment by shin202** [comment]
Thanks for your report. But, this is not a bug. episodeId params must be the movie's episodeId, not serverId. You can get the movie's  episodeId in the movie information response. 😁
